export const imgURLs = [
  {
    itemNo: "204486",
    packageDimensions: `8 x 5.75 x 0.2 inches`,
    itemWeight: `2.39 ounces`,
    ASIN: `B092XBV2H4`,
    itemAbout: [
      `SEEDRA 15 Herb Seeds Variety Pack contains 15 herbs - Basil, Thyme, Lavender, Sage, Parsley, Chives, Rosemary, Tarragon, Oregano, Fennel, Mint, Cilantro, Dill, Savory, Lemon Mint. Free Tools - professional instructions, pH tester, 15 plant markers`,
      `Be sure of our quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee`,
      `Best gift for novice or skilled gardeners – surprise your loved ones or friends with our perfect herb variety pack as a gift for any occasion such as a birthday, anniversary, or special holiday`,
      `Proudly sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA customer service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/A1JINiGVodL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81qs4wiTrUL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81pifA-TDuL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81sck29Q1eL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81z0ivmhJ1L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91aINCvUwkL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71eQKlM0jJL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91KLTKa72jL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/811zaHdOK1L._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/1767a68a-1728-446e-8096-142ed70fea77/default.jobtemplate.mp4.480.mp4`
    ]
  },
  {
    itemNo: "211619",
    packageDimensions: `5.48 x 3.51 x 0.16 inches`,
    itemWeight: `0.176 ounces`,
    ASIN: `B097Q1MBYJ`,
    itemAbout: [
      `SEEDRA English Lavender Seeds - contains 600 seeds in 1 Pack and professional instructions created by PhD Helga George`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee`,
      `Lavender Common Uses: essential oils, soaps, cosmetics, perfumes, potpourri, decorations. Culinary: meat marinades, baked breads, salads, jams, teas, lemonades, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`, 
    ],
    url: [
      `https://m.media-amazon.com/images/I/91O5BAUxY1L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81oCpW0AntS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1weVgEA-oL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91irdUBOIvL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91AyZDpQMFL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91fOtKKKEwL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91KrKq5cGrL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91kDMuS5C0L._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/27a8f06a-4905-4578-af61-d7d34267375c/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "502",
    packageDimensions: `5.94 x 3.7 x 0.55 inches`,
    itemWeight: `Item Weight`,
    ASIN: `B08ZYKRWHX`,
    itemAbout: [
      `SEEDRA Spinach Seeds - contains 300 seeds in 1 Pack and professional instructions created by PhD Helga George`,
      `Be Sure Of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee`,
      `Spinach Common Culinary Uses: salads, soups, smoothies, lasagne, pizza, pies, risotto, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/81Gunkyi7ML._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91DjxLL76nL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/817+R4n37hL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1C4dQg6p-L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81GxK9Sd04L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1n4G2nT8iL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91glgsK1hhL._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/d3ed260b-d320-4cdf-9331-8c05662fb892/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "181796",
    packageDimensions: `5.39 x 3.54 x 0.35 inches`,
    itemWeight: `0.634 ounces`,
    ASIN: `B08Z3HN5MP`,
    itemAbout: [
      `SEEDRA Cilantro Seeds - contains 300 seeds in 1 Pack and professional instructions created by PhD Helga George`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee`,
      `Cilantro Common Culinary Uses: salsa, guacamole, pesto, salads, chutney, baked breads, pad thai, pico de gallo, rice, grilled shrimp skewers, falafel, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91jeh6h28QS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1-gpoM5uMS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81f9pblsk4S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81+fIQ1oTBS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91B-lDnUlrS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/914qv0Vij2S._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/c9df7ffa-9652-4979-81e7-89b6890d3496/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "822862",
    packageDimensions: `5.43 x 3.5 x 1.89 inches`,
    itemWeight: `1.44 ounces`,
    ASIN: `B08YFHHQ3N`,
    itemAbout: [
      `SEEDRA Basil – Italian Large Leaf - contains 300 seeds in 1 Pack and professional instructions created by PhD Helga George`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee`,
      `Basil Common Culinary Uses: ravioli, pesto, sauces, pasta, noodles, salads, curry, pizza, soups, smoothies, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91Za3tk4mpL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/913rvzjXblL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81xyXvPww5L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91NEm5lv21L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81L9vLUnEGL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91iikQN6iHL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91B6PjSngyL._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/0377cd31-d534-40f3-92f1-04e105860a63/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "865636",
    packageDimensions: `5.47 x 3.5 x 0.35 inches`,
    itemWeight: `1.44 ounces`,
    ASIN: `B0968NLM7N`,
    itemAbout: [
      `SEEDRA Wildflower Mix Seeds - contains 999 seeds in 1 Pack - Bachelor Button/Cornflower, Siberian Wallflower, Chinese Houses, Coreopsis Lance Leaf, Sweet William, Foxglove, Purple Coneflower, California Poppy, Annual Baby's Breath, Dames Rocket, Rose Mallow, Toadflax/Spurred Snapdragon, Scarlet Flax, Lemon Mint, Alpine Forget Me Not, Five Spot, Baby Blue Eyes, Evening Primrose, Annual Phlox (Red), Catchfly, Red Corn Poppy, Shirley Poppy (Mixed)`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee`,
      `Wildflower Common Uses: healing herbal ointments, tinctures, cosmetics, soaps, decorations, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91FmRd6o+xS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/919F6Pl3sNS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81X8P-BsPPS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91lDDQwyHBS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91Ci0NzspkS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1044QJI9gS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91nfiXO905S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1Mjr4udNjS._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/1f420ce4-42a7-40db-a594-103e0219a7f5/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "914887",
    packageDimensions: `5 x 3.55 x 0.01 inches`,
    itemWeight: `0.81 ounces`,
    ASIN: `B08Y5RT1LZ`,
    itemAbout: [
      `SEEDRA Dill Bouquet Seeds - contains 300 seeds in 1 Pack and professional instructions created by PhD Helga George`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee`,
      `Dill Common Culinary Uses: pickles, salads, pesto, creamy sauces, noodles, smoothies, baked breads, fritters, soups, yoghurts, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/913zPhwHBcL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71WQfbjQ9vL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91aEv+rgNmL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91-kt0dZURL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/916AG0UvUzL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91OadBjBh-L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1bBoPmGVZL._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/55fdc556-2d56-4944-a678-05adc211cf95/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "345426",
    packageDimensions: `5.43 x 3.5 x 0.28 inches`,
    itemWeight: `0.317 ounces`,
    ASIN: `B0964CZ2PF`,
    itemAbout: [
      `SEEDRA Marigold - Petite Mix Seeds - contains 999 seeds in 1 Pack `,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Marigold Common Uses: healing herbal ointments, tinctures, topical treatments, cosmetics, soaps, decorations, poultry feed, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91s1QfLyNrL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81IQVyLyMVL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/61HQsEB-XQL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81grqTYSeVL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71sY5ldFTWL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/715dbixKgfL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81xdoL6z0cL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71nD9siqb8L._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/f711bac7-c4ac-4402-b113-135a2445a9b6/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "699319",
    packageDimensions: `5.51 x 3.43 x 0.35 inches`,
    itemWeight: `0.317 ounces`,
    ASIN: `B0968K5GTW`,
    itemAbout: [
      `SEEDRA Okra - Clemson Spineless - contains 300 seeds in 2 Packs and professional instructions `,
      `Be Sure Of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Okra Common Culinary Uses: pickling, salads, casserole, kebabs, gumbo, creole, soups, okra fries and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91xO0e74XMS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91gz5Uk8zaS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81iJnteARhS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1mt49yFuqS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81m82GoqAVS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1NYhc7scuS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91XHvMv8LkS._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/3e6f52b4-8c57-4c81-99af-c5bcd7ad8449/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "680201",
    packageDimensions: `5.56 x 3.51 x 0.16 inches`,
    itemWeight: `0.176 ounces`,
    ASIN: `B08YR7D77G`,
    itemAbout: [
      `SEEDRA Parsley Seeds - Dark Green Italian flat-leaf - contains 300 seeds in 1 Pack and professional instructions created by PhD Helga George`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Parsley Common Culinary Uses: ravioli, pesto, quiche, salads, salsa, marinades, soups, smoothies, and more `,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91GhccsjbvL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91gXZ-6sPiL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81EtURCJORL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91ovMo8l+8L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91hRaiHty7L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91LiQ-V1vTL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81YRu9IMGsL._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/297a0725-b814-4185-93b9-7ae24cdbede2/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "601020",
    packageDimensions: `5.43 x 3.5 x 0.35 inches`,
    itemWeight: `0.317 ounces`,
    ASIN: `B0968P124N`,
    itemAbout: [
      `SEEDRA Corn - Bodacious Hybrid - contains 70 seeds in 1 Pack and professional instructions `,
      `Be Sure Of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Corn Common Culinary Uses: salads, stir-fries, pastas, dips, succotash, pudding, tacos, soups, pizzas, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/9125PQypA4S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91hnsReV0GS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/714hhXhzX9S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81FAgYZrzwS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71TeqjhrzHS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1txUPvIP2S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91Wce4ZwwRS._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/91eb5c27-e187-4e5e-bab6-51822db0efa3/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "430513",
    packageDimensions: `5.44 x 3.51 x 0.16 inches`,
    itemWeight: `0.317 ounces`,
    ASIN: `B0964FYX8S`,
    itemAbout: [
      `SEEDRA Cucumber - National Pickling - contains 120 seeds in 1 Pack and professional instructions`,
      `Be Sure Of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Cucumber Common Culinary Uses: pickling, salads, cocktails, tacos, fritters, soups, tartare, paletas, and more `,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91VgieburoS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91COOXMMo-S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71kHCWw8uGS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91X3rHxgg6S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91wTY0PzIZS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A10J6x6rtES._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91PWjl-R8hS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71p7G4HzY3S._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "131449",
    packageDimensions: `8.54 x 5.79 x 0.63 inches`,
    itemWeight: `2.29 ounces`,
    ASIN: `B09DB2B7D3`,
    itemAbout: [
      `SEEDRA Сarrot Seeds Variety Pack contains 6 carrots - Chantenay Red Cored, Imperator, Scarlet Nantes, Solar Yellow, Lunar White, Black Nebula. Free Tools - professional instructions, pH tester, 6 plant markers.`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee! `,
      `Best Gift for Novice or Skilled Gardeners - our awesome mixture of carrots will add fabulous color and zip to your everyday and special meals! `,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91T245iEpHL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/817hcOKXk9L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81H6MQRtUgL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81PAcutm1GL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81MC0Dr+2PL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91Q0qNwEXTL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71SUYYSgiXL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/813bXwcUY7L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/8128dbTM1cL._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "954601",
    packageDimensions: `8.46 x 5.71 x 1.34 inches`,
    itemWeight: `5 ounces`,
    ASIN: `B09D9YLVYZ`,
    itemAbout: [
      `SEEDRA Bean Seeds Variety Pack contains 4 beans - Royal Burgundy, Henderson Lima Bush, Shell - Pinto, Golden Wax. Free Tools - professional instructions, pH tester, 4 plant markers. `,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee! `,
      `Best Gift for Novice or Skilled Gardeners - the best possible blended mixture of multicolor beans available - burgundy, yellow, green, and red beans for any and all tastes! `,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/913SN14BSUL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71EEJZjUD0L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81yDW2SasbL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81kKR-PPz6L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1pzbpPHOEL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/917DpuM6WHL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71y+3aLVjXL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81GOcB3SNeL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/913X7Pg9SBL._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "889873",
    packageDimensions: `8.43 x 5.75 x 1.38 inches`,
    itemWeight: `3.52 ounces`,
    ASIN: `B09DB1ZJQ5`,
    itemAbout: [
      `SEEDRA Pepper Seeds Variety Pack contains 11 Hot and Sweet peppers. HOT - Cayenne Long Red, Anaheim Chili, Habanero Orange, Hungarian Yellow Wax, Large Red Cherry, Tam Jalapeño, Pasilla Bajio, Mulato Isleno, and SWEET - Big Red Bell Pepper, Golden Cal Wonder, California Wonder. Free Tools - professional instructions, pH tester, 11 plant markers.`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee! `,
      `Best Gift for Novice or Skilled Gardeners - spice up your meals with the most colorful variety of peppers! `,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91kUYawXRGL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81HcjlE8r+L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81qHqlc9YEL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81vCAANYFeL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91lI2LJePRL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91mo87URFuL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71ngJpFCliL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81qAophP5EL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81BCNwpVe8L._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "793666",
    packageDimensions: `8.03 x 5.79 x 1.34 inches`,
    itemWeight: `3.8 ounces`,
    ASIN: `B09D9ZF31J`,
    itemAbout: [
      `SEEDRA Radish Seeds Variety Pack contains 9 radishes - Watermelon, German Giant, Purple Plum, French Breakfast, Cherry Belle, Champion, White Icicle, Black Spanish Round Winter, Japanese Minowase Winter (Daikon). Free Tools - professional instructions, pH tester, 9 plant markers.`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee! `,
      `Best Gift for Novice or Skilled Gardeners - try out our perfect assortment of radishes - eat now, pickle, or roast! `,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91I46b6BiXL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81LaonTTDoL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81V3il6wh0L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81QBtDairFL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81FrlrDxh+L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/911GRdl1y5L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71wQLZ553vL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91Z0rSzKr0L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/812J-O021VL._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "252791",
    packageDimensions: `5.56 x 3.58 x 0.01 inches`,
    itemWeight: `0.176 ounces`,
    ASIN: `B095V3Z5P1`,
    itemAbout: [
      `SEEDRA Lettuce Buttercrunch - contains 600 seeds in 1 Pack and professional instructions `,
      `Be Sure Of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Lettuce Common Culinary uses: salads, sauces, smoothies, spring rolls, soups, tacos, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91gY2bGUn4S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91lC382M9jS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/817ozCPmZ7S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81wWjMxzj2S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91lzvR8JlqS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1xiaqKACgS._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/be01dbee-0e69-4603-a24a-39b36a1c218e/default.jobtemplate.mp4.480.mp4`,
    ]
  },
  {
    itemNo: "351153",
    packageDimensions: `8 x 4 x 0.5 inches`,
    itemWeight: `3 ounces`,
    ASIN: `B09D9ZRYM6`,
    itemAbout: [
      `SEEDRA Beet Seeds Variety Pack contains 5 beets - Chioggia, Cylindra, Detroit Dark Red, Ruby Queen, Bulls Blood. Free Tools - professional instructions, pH tester, 5 plant markers.`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee!`,
      `Best Gift for Novice or Skilled Gardeners - don't hesitate to try our special mix of extraordinary beets - they are definitely worth it!`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91vlm35yyZL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81ULfHLZgYL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81Hvj7+QUqL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81uVMVoxEeL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91BQsyzK6GL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91Jn8NnR2xL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71+SU3LZEiL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81EKUYCVWBL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91svzbdvJRL._AC_SL1500_.jpg`,

    ]
  },
  {
    itemNo: "457886",
    packageDimensions: `8.5 x 5.75 x 0.87 inches`,
    itemWeight: `2.85 ounces`,
    ASIN: `B09DB1J93Z`,
    itemAbout: [
      `SEEDRA Onion Seeds Variety Pack contains 8 onions - Walla Walla, Yellow Sweet Spanish, Crystal White Wax, Tokyo Long White Bunching, Southport Red Globe, White Sweet Spanish, Crimson Forest Bunching, Tropeana Lunga. Free Tools - professional instructions, pH tester, 8 plant markers.`,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee! `,
      `Best Gift for Novice or Skilled Gardeners - a perfect variety of yellow, red, white, and green onions for cooking!`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91MdUTdwJAL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81lMFcgH86L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81bygqOJnxL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81liNA5wamL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91LUFpMF0YL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91oSePhF3OL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71kHy2+J-+L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/819NMw1PEsL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81YXkt6v39L._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "219571",
    packageDimensions: `5.47 x 3.5 x 0.35 inches`,
    itemWeight: `1.44 ounces`,
    ASIN: `B0968NLM7N`,
    itemAbout: [
      `SEEDRA Wildflower Mix Seeds - contains 999 seeds in 1 Pack - Bachelor Button/Cornflower, Siberian Wallflower, Chinese Houses, Coreopsis Lance Leaf, Sweet William, Foxglove, Purple Coneflower, California Poppy, Annual Baby's Breath, Dames Rocket, Rose Mallow, Toadflax/Spurred Snapdragon, Scarlet Flax, Lemon Mint, Alpine Forget Me Not, Five Spot, Baby Blue Eyes, Evening Primrose, Annual Phlox (Red), Catchfly, Red Corn Poppy, Shirley Poppy (Mixed) `,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Wildflower Common Uses: healing herbal ointments, tinctures, cosmetics, soaps, decorations, and more`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91FmRd6o+xS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/919F6Pl3sNS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81X8P-BsPPS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91lDDQwyHBS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91Ci0NzspkS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1044QJI9gS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91nfiXO905S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1Mjr4udNjS._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "712702",
    packageDimensions: `5.47 x 3.5 x 0.35 inches`,
    itemWeight: `1.44 ounces`,
    ASIN: `B0968NLM7N`,
    itemAbout: [
      `SEEDRA Wildflower Mix Seeds - contains 999 seeds in 1 Pack - Bachelor Button/Cornflower, Siberian Wallflower, Chinese Houses, Coreopsis Lance Leaf, Sweet William, Foxglove, Purple Coneflower, California Poppy, Annual Baby's Breath, Dames Rocket, Rose Mallow, Toadflax/Spurred Snapdragon, Scarlet Flax, Lemon Mint, Alpine Forget Me Not, Five Spot, Baby Blue Eyes, Evening Primrose, Annual Phlox (Red), Catchfly, Red Corn Poppy, Shirley Poppy (Mixed) `,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Wildflower Common Uses: healing herbal ointments, tinctures, cosmetics, soaps, decorations, and more `,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91FmRd6o+xS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/919F6Pl3sNS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81X8P-BsPPS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91lDDQwyHBS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91Ci0NzspkS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1044QJI9gS._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91nfiXO905S._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/A1Mjr4udNjS._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "347920",
    packageDimensions: `10 x 7.1 x 2 inches`,
    itemWeight: `1.6 ounces`,
    ASIN: `B00T84UPDQ`,
    itemAbout: [
      `SEEDRA Spinach Seeds Variety Pack contains 4 individual packets - Bloomsdale, New Zealand (Hot Weather), Space, Virofly. Free Tools - professional instructions, pH tester, 4 plant markers. `,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee! `,
      `Best Gift for Novice or Skilled Gardeners - being one of the healthiest vegetables, fresh spinach will enrich you with many healthful vitamins and minerals! `,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/910fkzDygqL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/8119vO5OI-L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81tF-srcPIL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/814fjE1Rj7L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/916Dtv7vZIL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91GWU8+greL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71Gpd+IDt+L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/816WAZLhKwL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81ikDHq5X0L._AC_SL1500_.jpg`,

    ]
  },
  {
    itemNo: "844233",
    packageDimensions: `3.15 x 1.97 x 0.24 inches`,
    itemWeight: `3.2 ounces`,
    ASIN: `B08RZ7V1H5`,
    itemAbout: [
      `SEEDRA 12 Herb Seeds Variety Pack contains 12 herbs - Basil, Thyme, Lavender, Sage, Parsley, Chives, Rosemary, Tarragon, Oregano, Fennel, Mint, Cilantro. Free Tools - professional instructions, pH tester, 12 plant markers `,
      `Be Sure of Our Quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee `,
      `Best Gift for Novice or Skilled Gardeners – surprise your loved ones or friends with our perfect herb variety pack as a gift for any occasion such as a birthday, anniversary, or special holiday`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/91PmQ9TiQQL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71Uild0A07L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81rZXhEC+mL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81w34jNLzbL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81pNfn8jDIL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91CRuim4wLL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71gXjPqOYFL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91eD56WsDoL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81Gv1fcNnLL._AC_SL1500_.jpg`,
    ]
  },
  {
    itemNo: "912281",
    packageDimensions: `8 x 5.75 x 0.2 inches`,
    itemWeight: `2.39 ounces`,
    ASIN: `B092XBV2H4`,
    itemAbout: [
      `SEEDRA 15 Herb Seeds Variety Pack contains 15 herbs - Basil, Thyme, Lavender, Sage, Parsley, Chives, Rosemary, Tarragon, Oregano, Fennel, Mint, Cilantro, Dill, Savory, Lemon Mint. Free Tools - professional instructions, pH tester, 15 plant markers`,
      `Be sure of our quality - the freshest batches of this season. Non-GMO, Heirloom - our seeds were tested and have the best germination ratings. Your easy growing experience is our guarantee`,
      `Best gift for novice or skilled gardeners – surprise your loved ones or friends with our perfect herb variety pack as a gift for any occasion such as a birthday, anniversary, or special holiday`,
      `Proudly Sourced in the USA - our garden seeds are grown, harvested, and packaged in the USA. We support local farmers and are happy to produce this American-made product`,
      `SEEDRA Customer Service - please contact us directly through Amazon with any questions or concerns about our products. We care about each customer and do our best to provide you with 100% satisfaction`,
    ],
    url: [
      `https://m.media-amazon.com/images/I/A1JINiGVodL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81qs4wiTrUL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81pifA-TDuL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81sck29Q1eL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/81z0ivmhJ1L._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91aINCvUwkL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/71eQKlM0jJL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/91KLTKa72jL._AC_SL1500_.jpg`,
      `https://m.media-amazon.com/images/I/811zaHdOK1L._AC_SL1500_.jpg`,
      // `https://m.media-amazon.com/images/S/vse-vms-transcoding-artifact-us-east-1-prod/1767a68a-1728-446e-8096-142ed70fea77/default.jobtemplate.mp4.480.mp4`,
    ]
  },
]